### PR TITLE
Adapt preset categories to new database entries

### PR DESCRIPTION
**Pull request by jkbe**

### CODE REVIEW

**Review by flowirtz — CHANGES_REQUESTED** [review]
I don't find that category name descriptive enough as I don't understand it.
Do you mean Results of studies or what is included in "Research Outputs"?
Also, lets stick to singular words.

**Comment by jkbe** [comment]
Research Output includes research activity and results. The two websites I added are databases that focus on recording papers and especially the data behind them and making it accessible for free. They're not restricted to a specific field, thus the category name.
Why just one word?

**Review by flowirtz — APPROVED** [review]
I see. I still don't find the category name self explanatory, but as I can't think of another solution atm I'll rather approve it :blush:

**Comment by flowirtz** [comment]
> Why just one word?

I think we misunderstood each other: I only wanted the category name to be without the "-s" at the end, as all others are as well.

**Pull request merged**
